# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 李涛
email: onresume@live.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://litao0621.github.io # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  litao0621

theme_color: light

# Theme
remote_theme: 'internet-de-france/athena'

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""

# Stastic UI
remote_theme_layouts: 
  - ""
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
